Add missing mlflow-faculty dependency
Required to be able to handle the faculty artifact scheme, otherwise
would end up throwing an error like this:
```
mlflow.exceptions.MlflowException: Could not find a registered artifact repository for: faculty-datasets:123/.mlflow-artifacts/3/abc/xyz. Currently registered schemes are: ['', 'file', 's3', 'gs', 'wasbs', 'ftp', 'sftp', 'dbfs', 'hdfs', 'runs']
```

Signed-off-by: Gergely Imreh <gergely.imreh@faculty.ai>